# Generated by Django 4.2.4 on 2023-08-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='page',
            field=models.ManyToManyField(choices=[(1, 'one'), (2, 'two')], related_name='block', to='page_content.page'),
        ),
    ]
