# Generated by Django 4.2.4 on 2023-08-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_content', '0002_alter_block_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='sort_block',
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_index', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_content.page')),
            ],
        ),
        migrations.AlterField(
            model_name='block',
            name='page',
            field=models.ManyToManyField(related_name='block', to='page_content.pageblock'),
        ),
    ]
